#!/usr/bin/php
<?php
$doc = <<<DOC
Generate secure cryptographic hashes using bcrypt.

Usage:
    bcrypt-hash [-c <cost>] <plaintext>
    bcrypt-hash (-h | --help)
    bcrypt-hash (-v | --version)

Options:
    -h --help       Show this screen.
    -v --version    Show version.
    -c <cost>       bcrypt cost parameter [default: 10].

DOC;

# Generate the bcrypt hash using the specified plaintext and cost, while generating the salt
# automatically (as is recommended)
function bcrypt_hash($plaintext, $cost) {
    # Ensure cost parameter is between 04 and 32 (limits specified by the PHP crypt() function)
    if (($cost >= 04) && ($cost <= 31)) {
        $options = [
            'cost' => sprintf("%02d", $cost),
        ];
    }

    # Default to a cost parameter of 10 (1024 rounds) if out of range or not specified
    else {
        $options = [
            'cost' => 10,
        ];
    }

    # Generate hash
    $hash = password_hash($plaintext, PASSWORD_BCRYPT, $options);

    return $hash;
}

# docopt argument processing
require('docopt/src/docopt.php');
$args = Docopt::handle($doc, array('version'=>'bcrypt-hash 0.1.0'));

$cost =  $args['-c'];
$plaintext = $args['<plaintext>'];

$hash = bcrypt_hash($plaintext, $cost);

echo $hash;
?>
